info:
  resistance: null
name: straight_heater_metal_undercut_47ed7538
ports:
  l_e2:
    center:
    - -10.4
    - 5.5
    layer:
    - 49
    - 0
    name: l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 320.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  r_e2:
    center:
    - 330.4
    - 5.5
    layer:
    - 49
    - 0
    name: r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  cross_section: xs_sc
  cross_section_heater: xs_heater_metal
  cross_section_heater_undercut: xs_sc_heater_metal_undercut
  cross_section_waveguide_heater: xs_sc_heater_metal
  heater_taper_length: 5.0
  length: 320.0
  length_straight: 0.1
  length_straight_input: 15.0
  length_undercut: 30.0
  length_undercut_spacing: 6.0
  ohms_per_square: null
  port_orientation1: 90
  port_orientation2: 90
  via_stack: via_stack_heater_mtop
  with_undercut: false
