info: {}
name: grating_coupler_loss_fiber_array
ports: {}
settings:
  cross_section: xs_sc
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  pitch: 127.0
  port_name: o1
