info:
  add_bbox: null
  add_pins: true
  child_name: straight_length20_width2_add_tapers_277b1a4a
  component:
    component: straight
    settings:
      add_bbox: null
      add_pins: true
      cross_section: xs_sc
      layer: null
      length: 20
      npoints: 2
      width: 2
  cross_section: xs_sc
  grating_coupler:
    period: 0.676
    polarization: te
    wavelength: 1.53
  layer: null
  length: 20
  npoints: 2
  ports: null
  route_info:
    length: 20
    type: xs_2df11454
    weight: 20
    xs_2df11454_length: 20
  select_ports:
    function: select_ports
    settings:
      port_type: optical
  taper:
    function: taper
  taper_port_name1: o1
  taper_port_name2: o2
  width: 2
name: straight_length20_width2_add_tapers_277b1a4a_add_fiber_array_250d3a78
ports:
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-loopback_1:
    center:
    - -180.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-loopback_1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-loopback_4:
    center:
    - 200.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-loopback_4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-o1:
    center:
    - -53.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-o1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-o2:
    center:
    - 73.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2_add_tapers_277b1a4a-o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  component:
    component: add_tapers
    settings:
      component:
        component: straight
        settings:
          add_bbox: null
          add_pins: true
          cross_section: xs_sc
          layer: null
          length: 20
          npoints: 2
          width: 2
      ports: null
      select_ports:
        function: select_ports
        settings:
          port_type: optical
      taper:
        function: taper
      taper_port_name1: o1
      taper_port_name2: o2
  component_name: null
  cross_section: xs_sc
  gc_port_labels: null
  gc_port_name: o1
  get_input_labels_function:
    function: get_input_labels
    settings:
      get_input_label_text_function:
        function: get_input_label_text_dash
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  layer_label: null
  optical_routing_type: 0
  select_ports:
    function: select_ports
    settings:
      port_type: optical
