info: {}
name: mzi_7a18d033
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 281.02
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  top_l_e1:
    center:
    - 19.6
    - 22.625
    layer:
    - 49
    - 0
    name: top_l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e2:
    center:
    - 25.1
    - 28.125
    layer:
    - 49
    - 0
    name: top_l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e3:
    center:
    - 30.6
    - 22.625
    layer:
    - 49
    - 0
    name: top_l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e4:
    center:
    - 25.1
    - 17.125
    layer:
    - 49
    - 0
    name: top_l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e1:
    center:
    - 240.4
    - 22.625
    layer:
    - 49
    - 0
    name: top_r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e2:
    center:
    - 245.9
    - 28.125
    layer:
    - 49
    - 0
    name: top_r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e3:
    center:
    - 251.4
    - 22.625
    layer:
    - 49
    - 0
    name: top_r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e4:
    center:
    - 245.9
    - 17.125
    layer:
    - 49
    - 0
    name: top_r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  add_optical_ports_arms: false
  bend:
    function: bend_euler
  combiner: null
  cross_section: xs_sc
  cross_section_x_bot: null
  cross_section_x_top: null
  delta_length: 10.0
  length_x: 200
  length_y: 2.0
  mirror_bot: false
  nbends: 2
  port_e0_combiner: o3
  port_e0_splitter: o3
  port_e1_combiner: o2
  port_e1_splitter: o2
  splitter: mmi1x2
  straight:
    function: straight
  straight_x_bot: null
  straight_x_top: straight_heater_metal
  straight_y: null
  with_splitter: true
