info: {}
name: awg
ports:
  E0:
    center:
    - 54.75
    - -0.0
    layer:
    - 1
    - 0
    name: E0
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  E1:
    center:
    - 50.0
    - 0.0
    layer:
    - 1
    - 0
    name: E1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  E2:
    center:
    - 45.25
    - 0.0
    layer:
    - 1
    - 0
    name: E2
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  arms: 10
  fpr_spacing: 50.0
  free_propagation_region_input_function:
    function: free_propagation_region
    settings:
      inputs: 1
  free_propagation_region_output_function:
    function: free_propagation_region
    settings:
      inputs: 10
      width1: 10
      width2: 20.0
  outputs: 3
