info: {}
name: ring_single_bend_coupler
ports:
  o1:
    center:
    - -16.0
    - 15.7
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 16.0
    - 15.7
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend:
    function: bend_circular
  coupling_angle_coverage: 180.0
  cross_section_inner: xs_sc
  cross_section_outer: xs_sc
  gap: 0.2
  length_x: 0.6
  length_y: 0.6
  radius: 5.0
