info:
  instances:
  - s
  - b
name: sample_mirror_simple_0e62769d
ports: {}
settings:
  conf:
    connections:
      b,o1: s,o2
    instances:
      b:
        component: bend_circular
      s:
        component: straight
    name: sample_mirror_simple
    placements:
      b:
        mirror: true
        port: o1
  label_instance_function:
    function: add_instance_label
  mode: layout
  routing_strategy:
    get_bundle:
      function: get_bundle
    get_bundle_all_angle:
      function: get_bundle_all_angle
    get_bundle_electrical:
      function: get_bundle
      settings:
        bend:
          function: wire_corner
        cross_section: xs_metal_routing
    get_bundle_from_steps:
      function: get_bundle_from_steps
    get_bundle_from_steps_electrical:
      function: get_bundle_from_steps
      settings:
        bend:
          function: wire_corner
        cross_section: xs_metal_routing
    get_bundle_from_waypoints:
      function: get_bundle_from_waypoints
    get_bundle_path_length_match:
      function: get_bundle_path_length_match
    get_bundle_same_axis_no_grouping:
      function: get_bundle_same_axis_no_grouping
  validate: false
