info:
  N: 6
  asymmetric_cross_section: false
  bend180:
    function: bend_euler
    settings:
      angle: 180
  bend90:
    function: bend_euler
  child_name: spiral_inner_io_fiber_single
  cross_section: xs_sc
  cross_section_bend: null
  cross_section_bend180: null
  cross_section_ports: null
  grating_spacing: 200.0
  length: 9973.393
  polarization: te
  straight:
    function: straight
  waveguide_spacing: 3.0
  wavelength: 1.53
  x_straight_inner_left: 75.0
  x_straight_inner_right: 40.0
  y_straight_inner_bottom: 0.0
  y_straight_inner_top: 10.0
name: spiral_inner_io_fiber_single_add_grating_couplers_with_loopback_fiber_single
ports:
  loopback1:
    center:
    - 67.473
    - -10.0
    layer:
    - 1
    - 0
    name: loopback1
    orientation: 270.0
    port_type: loopback
    shear_angle: null
    width: 0.5
  loopback2:
    center:
    - 67.473
    - 210.0
    layer:
    - 1
    - 0
    name: loopback2
    orientation: 90.0
    port_type: loopback
    shear_angle: null
    width: 0.5
  o1:
    center:
    - 0.0
    - -10.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 0.0
    - 210.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  component: spiral_inner_io_fiber_single
  component_name: null
  cross_section:
    function: cross_section
    settings:
      add_pins_function_name: add_pins_inside1nm
  gc_port_name: o1
  get_input_label_text_loopback_function:
    function: get_input_label_text
    settings:
      prefix: loopback_
  get_input_labels_function:
    function: get_input_labels
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  layer_label: null
  loopback_xspacing: 5.0
  rotation: 90
  select_ports:
    function: select_ports
    settings:
      port_type: optical
  with_loopback: true
