info:
  bend_s:
    add_pins: true
    bend_radius_error_type: null
    child_name: bezier_ed99a725
    control_points:
    - - 0
      - 0
    - - 45.0
      - 0
    - - 45.0
      - 11.875
    - - 90.0
      - 11.875
    cross_section: xs_sc
    end_angle: 0
    length: 91.103
    min_bend_radius: 129.147
    npoints: 99
    start_angle: 0
    with_bbox: true
    with_manhattan_facing_angles: true
name: splitter_tree
ports:
  o1_0_0:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1_0_0
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_1_1:
    center:
    - 195.5
    - -12.5
    layer:
    - 1
    - 0
    name: o2_1_1
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_1_2:
    center:
    - 195.5
    - -37.5
    layer:
    - 1
    - 0
    name: o2_1_2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_1_3:
    center:
    - 195.5
    - 37.5
    layer:
    - 1
    - 0
    name: o2_1_3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_1_4:
    center:
    - 195.5
    - 12.5
    layer:
    - 1
    - 0
    name: o2_1_4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend_s:
    function: bend_s
  bend_s_xsize: null
  coupler:
    function: mmi1x2
  cross_section: xs_sc
  noutputs: 4
  spacing:
  - 90.0
  - 50.0
