info:
  child_name: straight_heater_metal_undercut_954d6e94_add_pads_bot_07036936
  resistance: null
name: straight_heater_metal_undercut_954d6e94_add_pads_bot_07036936_add_pads_top_07036936
ports:
  elec-pad_sizepad_size-straight_heater_metal_undercut_954d6e94-l_e1:
    center:
    - -15.9
    - 46.5
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-straight_heater_metal_undercut_954d6e94-l_e1
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  l_e1:
    center:
    - -15.9
    - 0.0
    layer:
    - 49
    - 0
    name: l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e2:
    center:
    - -10.4
    - -5.5
    layer:
    - 49
    - 0
    name: l_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e3:
    center:
    - -4.9
    - 0.0
    layer:
    - 49
    - 0
    name: l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e4:
    center:
    - -10.4
    - 5.5
    layer:
    - 49
    - 0
    name: l_e4
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 100.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  r_e1:
    center:
    - 104.9
    - 0.0
    layer:
    - 49
    - 0
    name: r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e2:
    center:
    - 110.4
    - -5.5
    layer:
    - 49
    - 0
    name: r_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e3:
    center:
    - 115.9
    - 0.0
    layer:
    - 49
    - 0
    name: r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e4:
    center:
    - 110.4
    - 5.5
    layer:
    - 49
    - 0
    name: r_e4
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  component:
    component: straight_heater_metal_undercut
    settings:
      cross_section: xs_sc
      cross_section_heater: xs_heater_metal
      cross_section_heater_undercut: xs_sc_heater_metal_undercut
      cross_section_waveguide_heater: xs_sc_heater_metal
      heater_taper_length: 5.0
      length: 100.0
      length_straight: 0.1
      length_straight_input: 15.0
      length_undercut: 30.0
      length_undercut_spacing: 6.0
      ohms_per_square: null
      port_orientation1: null
      port_orientation2: null
      via_stack: via_stack_heater_mtop
      with_undercut: false
  port_names:
  - l_e1
