info:
  child_name: mmi1x2
  cross_section: xs_sc
  gap_mmi: 0.25
  length_mmi: 5.5
  length_taper: 10.0
  straight:
    function: straight
  taper:
    function: taper
  width: null
  width_mmi: 2.5
  width_taper: 1.0
  with_bbox: true
name: mmi1x2_splitter_chain
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 15.5
    - -0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 52.0
    - 1.8
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 88.5
    - 4.225
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o5:
    center:
    - 88.5
    - 5.475
    layer:
    - 1
    - 0
    name: o5
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend:
    function: bend_s
  columns: 3
  splitter:
    function: mmi1x2
