info:
  add_optical_ports_arms: false
  bend:
    function: bend_euler
  child_name: mzi_2e88f57c_add_pads_bot_b2f49b9e
  combiner:
    function: mmi2x2
  component:
    component: mzi
    settings:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: xs_sc
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
  component_name: null
  cross_section: xs_sc
  cross_section_x_bot: null
  cross_section_x_top: null
  delta_length: 10.0
  get_input_labels_function: null
  layer_label: TEXT
  length_x: 0.1
  length_y: 2.0
  mirror_bot: false
  nbends: 2
  optical_routing_type: 1
  pad:
    function: pad
    settings:
      size: pad_size
  pad_port_labels: null
  pad_port_name: e1
  pad_spacing: pad_spacing
  port_e0_combiner: o4
  port_e0_splitter: o4
  port_e1_combiner: o3
  port_e1_splitter: o3
  port_names: null
  select_ports:
    function: select_ports
    settings:
      port_type: electrical
  splitter:
    function: mmi2x2
  straight:
    function: straight
  straight_separation: null
  straight_x_bot: null
  straight_x_top: straight_heater_metal
  straight_y: null
  with_splitter: true
name: mzi_2e88f57c_add_pads_bot_b2f49b9e_add_pads_top_b2f49b9e
ports:
  elec-pad_sizepad_size-mzi_2e88f57c-top_l_e1:
    center:
    - -296.4
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_l_e1
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  elec-pad_sizepad_size-mzi_2e88f57c-top_l_e2:
    center:
    - -96.4
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_l_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  elec-pad_sizepad_size-mzi_2e88f57c-top_l_e3:
    center:
    - 103.6
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_l_e3
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  elec-pad_sizepad_size-mzi_2e88f57c-top_l_e4:
    center:
    - 403.6
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  elec-pad_sizepad_size-mzi_2e88f57c-top_r_e1:
    center:
    - -196.4
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_r_e1
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  elec-pad_sizepad_size-mzi_2e88f57c-top_r_e2:
    center:
    - 3.6
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_r_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  elec-pad_sizepad_size-mzi_2e88f57c-top_r_e3:
    center:
    - 203.6
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_r_e3
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  elec-pad_sizepad_size-mzi_2e88f57c-top_r_e4:
    center:
    - 303.6
    - 88.9
    layer:
    - 49
    - 0
    name: elec-pad_sizepad_size-mzi_2e88f57c-top_r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  o1:
    center:
    - -10.0
    - 0.625
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -10.0
    - -0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 117.12
    - -0.625
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 117.12
    - 0.625
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  top_l_e1:
    center:
    - 19.6
    - -22.625
    layer:
    - 49
    - 0
    name: top_l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e2:
    center:
    - 25.1
    - -28.125
    layer:
    - 49
    - 0
    name: top_l_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e3:
    center:
    - 30.6
    - -22.625
    layer:
    - 49
    - 0
    name: top_l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e4:
    center:
    - 25.1
    - -17.125
    layer:
    - 49
    - 0
    name: top_l_e4
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e1:
    center:
    - 76.5
    - -22.625
    layer:
    - 49
    - 0
    name: top_r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e2:
    center:
    - 82.0
    - -28.125
    layer:
    - 49
    - 0
    name: top_r_e2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e3:
    center:
    - 87.5
    - -22.625
    layer:
    - 49
    - 0
    name: top_r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e4:
    center:
    - 82.0
    - -17.125
    layer:
    - 49
    - 0
    name: top_r_e4
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  component:
    component: mzi
    settings:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: xs_sc
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
