info:
  centered: false
  child_name: rectangle_size1300__2600
  layer: WG
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  port_type: electrical
  size:
  - 1300
  - 2600
name: rectangle_size1300__2600_die_bbox
ports: {}
settings:
  component:
    function: rectangle
    settings:
      size:
      - 1300
      - 2600
  die_name: null
  layer: MTOP
  padding: 10.0
  street_length: null
  street_width: 100.0
  text_anchor: sw
  text_size: 100.0
