info: {}
name: ring_crow
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - -10.0
    - 62.8
    layer:
    - 1
    - 0
    name: o3
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 10.0
    - 62.8
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bends:
  - function: bend_circular
  - function: bend_circular
  - function: bend_circular
  gaps:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  input_straight_cross_section:
    function: cross_section
    settings:
      add_pins_function_name: add_pins_inside1nm
  output_straight_cross_section:
    function: cross_section
    settings:
      add_pins_function_name: add_pins_inside1nm
  radius:
  - 10.0
  - 10.0
  - 10.0
  ring_cross_sections:
  - function: cross_section
    settings:
      add_pins_function_name: add_pins_inside1nm
  - function: cross_section
    settings:
      add_pins_function_name: add_pins_inside1nm
  - function: cross_section
    settings:
      add_pins_function_name: add_pins_inside1nm
