info:
  N: 6
  asymmetric_cross_section: false
  bend180:
    function: bend_euler
    settings:
      angle: 180
  bend90:
    function: bend_euler
  child_name: spiral_inner_io_length20000p0
  cross_section: xs_sc
  cross_section_bend: null
  cross_section_bend180: null
  grating_spacing: 127.0
  length: 19999.999
  polarization: te
  straight:
    function: straight
  waveguide_spacing: 3.0
  wavelength: 1.53
  x_straight_inner_left: 50.0
  x_straight_inner_right: 150.0
  y_straight_inner_bottom: 10.0
  y_straight_inner_top: 50.0
name: spiral_inner_io_length20000p0_add_grating_couplers_with_loopback_fiber_array_with_loopbackFalse
ports:
  o1:
    center:
    - 0.0
    - 50.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 127.0
    - 50.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend:
    function: bend_euler
  component:
    component: spiral_inner_io
    settings:
      length: 20000.0
  component_name: null
  cross_section: xs_sc
  excluded_ports: null
  gc_port_name: o1
  gc_rotation: -90
  get_input_labels_function:
    function: get_input_labels
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  grating_separation: 127.0
  layer_label: null
  layer_label_loopback: null
  loopback_yspacing: 4.0
  nlabels_loopback: 2
  select_ports:
    function: select_ports
    settings:
      port_type: optical
  straight_separation: 5.0
  with_loopback: false
