info:
  length: 635.09
name: spiral_double
ports:
  o1:
    center:
    - 0.0
    - 22.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 0.0
    - -22.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend:
    function: bend_circular
  cross_section: xs_sc
  min_bend_radius: 10.0
  npoints: 1000
  number_of_loops: 3
  separation: 2.0
