info:
  child_name: bend_euler
  dy: 10.0
  length: 16.637
  radius: 10.0
  radius_min: 7.061
  route_info:
    length: 16.637
    n_bend_90: 1.0
    type: xs_sc
    weight: 16.637
    xs_sc_length: 16.637
  width: 0.5
name: bend_euler_add_trenches_cb24b746
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 10.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bot: true
  component:
    function: bend_euler
  cross_section: xs_rc_with_trenches
  left: false
  right: true
  top: false
