info:
  child_name: grating_coupler_elliptical_trenches_taper_angle35
  cross_section: xs_sc
  end_straight_length: 0.2
  fiber_angle: 15.0
  grating_line_width: 0.343
  layer_trench: SHALLOW_ETCH
  n_periods: 30
  ncladding: 1.443
  neff: 2.638
  p_start: 26
  period: 0.676
  polarization: te
  taper_angle: 35
  taper_length: 16.6
  trenches_extra_angle: 9.0
  wavelength: 1.53
name: grating_coupler_loss_fiber_single
ports: {}
settings:
  cross_section: xs_sc
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
