info:
  child_name: grating_coupler_elliptical_trenches_taper_angle35
  period: 0.676
  polarization: te
  wavelength: 1.53
name: grating_coupler_loss_fiber_single
ports: {}
settings:
  cross_section: xs_sc
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
