info:
  add_optical_ports_arms: false
  bend:
    function: bend_euler
  child_name: mzi_7a18d033_add_fiber_array_b2a215d5_1
  combiner: null
  component:
    component: mzi
    settings:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner: null
      cross_section: xs_sc
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 200
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o3
      port_e0_splitter: o3
      port_e1_combiner: o2
      port_e1_splitter: o2
      splitter: mmi1x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
  component_name: null
  cross_section: xs_sc
  cross_section_x_bot: null
  cross_section_x_top: null
  delta_length: 10.0
  fiber_spacing: 127.0
  gc_port_labels: null
  gc_port_name: o1
  get_input_labels_function:
    function: get_input_labels
    settings:
      get_input_label_text_function:
        function: get_input_label_text_dash
  grating_coupler:
    polarization: te
    wavelength: 1.554
  layer_label: null
  length_x: 200
  length_y: 2.0
  mirror_bot: false
  nbends: 2
  port_e0_combiner: o3
  port_e0_splitter: o3
  port_e1_combiner: o2
  port_e1_splitter: o2
  select_ports:
    function: select_ports
    settings:
      port_type: optical
  splitter: mmi1x2
  straight:
    function: straight
  straight_x_bot: null
  straight_x_top: straight_heater_metal
  straight_y: null
  with_loopback: true
  with_splitter: true
name: mzi_7a18d033_add_fiber_array_b2a215d5_1_add_fiber_array_optical_south_electrical_north
ports:
  e4_1_1:
    center:
    - 85.5
    - 129.656
    layer:
    - 49
    - 0
    name: e4_1_1
    orientation: 270
    port_type: electrical
    shear_angle: null
    width: 80.0
  e4_1_2:
    center:
    - 185.5
    - 129.656
    layer:
    - 49
    - 0
    name: e4_1_2
    orientation: 270
    port_type: electrical
    shear_angle: null
    width: 80.0
  opt-grating_coupler_elliptical-mzi_7a18d033-loopback_1:
    center:
    - -55.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-loopback_1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical-mzi_7a18d033-loopback_4:
    center:
    - 326.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-loopback_4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical-mzi_7a18d033-o1:
    center:
    - 72.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-o1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical-mzi_7a18d033-o2:
    center:
    - 199.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  analysis: ''
  analysis_settings: null
  anchor: sw
  component:
    function: mzi
    settings:
      length_x: 200
      straight_x_top: straight_heater_metal
  doe: ''
  electrical_port_names: null
  electrical_port_orientation: 90
  fiber_spacing: 127.0
  grating_coupler:
    function: grating_coupler_elliptical
  layer_label: TEXT
  measurement: optical_loopback2_heater_sweep
  measurement_settings: null
  npads: null
  pad:
    function: pad
    settings:
      size:
      - 80
      - 80
  pad_gc_spacing: 250.0
  pad_spacing: 100.0
  with_loopback: true
  xs_metal: xs_metal_routing
