info:
  child_name: dbr
  cross_section: xs_sc
  l1: 0.159
  l2: 0.159
  n: 10
  w1: 0.475
  w2: 0.525
name: dbr_cavity
ports:
  o1:
    center:
    - -10.0
    - -1.65
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.1
    - -1.65
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  component:
    function: dbr
  coupler: coupler
  gap: 0.2
  length: 0.1
