info:
  enclosure: 1.0
  size:
  - 0.7
  - 0.7
  spacing:
  - 2.0
  - 2.0
name: via
ports: {}
settings:
  bbox_layers: null
  bbox_offset: 0
  enclosure: 1.0
  gap: null
  layer: VIAC
  size:
  - 0.7
  - 0.7
  spacing:
  - 2.0
  - 2.0
