info:
  child_name: mzi_7a18d033_add_fiber_array_a7414e29_1
  grating_coupler:
    polarization: te
    wavelength: 1.554
name: mzi_7a18d033_add_fiber_array_a7414e29_1_add_fiber_array_optical_south_electrical_north
ports:
  e4_1_1:
    center:
    - 85.5
    - 129.656
    layer:
    - 49
    - 0
    name: e4_1_1
    orientation: 270
    port_type: electrical
    shear_angle: null
    width: 80.0
  e4_1_2:
    center:
    - 185.5
    - 129.656
    layer:
    - 49
    - 0
    name: e4_1_2
    orientation: 270
    port_type: electrical
    shear_angle: null
    width: 80.0
  opt-grating_coupler_elliptical-mzi_7a18d033-loopback_1:
    center:
    - -55.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-loopback_1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical-mzi_7a18d033-loopback_4:
    center:
    - 326.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-loopback_4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical-mzi_7a18d033-o1:
    center:
    - 72.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-o1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical-mzi_7a18d033-o2:
    center:
    - 199.0
    - -74.9
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical-mzi_7a18d033-o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  analysis: ''
  analysis_settings: null
  anchor: sw
  component:
    function: mzi
    settings:
      length_x: 200
      straight_x_top: straight_heater_metal
  doe: ''
  electrical_port_names: null
  electrical_port_orientation: 90
  fiber_spacing: 127.0
  grating_coupler:
    function: grating_coupler_elliptical
  layer_label: TEXT
  measurement: optical_loopback2_heater_sweep
  measurement_settings: null
  npads: null
  pad:
    function: pad
    settings:
      size:
      - 80
      - 80
  pad_gc_spacing: 250.0
  pad_spacing: 100.0
  with_loopback: true
  xs_metal: xs_metal_routing
