info: {}
name: array_with_fanout_2d
ports:
  o1_1_1:
    center:
    - -50.0
    - -85.0
    layer:
    - 1
    - 0
    name: o1_1_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o1_2_1:
    center:
    - -50.0
    - 65.0
    layer:
    - 1
    - 0
    name: o1_2_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_1_1:
    center:
    - -50.0
    - -75.0
    layer:
    - 1
    - 0
    name: o2_1_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2_2_1:
    center:
    - -50.0
    - 75.0
    layer:
    - 1
    - 0
    name: o2_2_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3_1_1:
    center:
    - -50.0
    - -65.0
    layer:
    - 1
    - 0
    name: o3_1_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3_2_1:
    center:
    - -50.0
    - 85.0
    layer:
    - 1
    - 0
    name: o3_2_1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  columns: 3
  pitch: 150.0
  pitch_x: null
  pitch_y: null
  rows: 2
