info: {}
name: ring_double_heater
ports:
  l_e1:
    center:
    - -6.0
    - 0.0
    layer:
    - 49
    - 0
    name: l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 4.0
  l_e2:
    center:
    - -4.0
    - 2.0
    layer:
    - 49
    - 0
    name: l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 4.0
  l_e3:
    center:
    - -2.0
    - 0.0
    layer:
    - 49
    - 0
    name: l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 4.0
  l_e4:
    center:
    - -4.0
    - -2.0
    layer:
    - 49
    - 0
    name: l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 4.0
  o1:
    center:
    - -14.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 13.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - -14.0
    - 21.41
    layer:
    - 1
    - 0
    name: o3
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 13.0
    - 21.41
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  r_e1:
    center:
    - 1.0
    - 0.0
    layer:
    - 49
    - 0
    name: r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 4.0
  r_e2:
    center:
    - 3.0
    - 2.0
    layer:
    - 49
    - 0
    name: r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 4.0
  r_e3:
    center:
    - 5.0
    - 0.0
    layer:
    - 49
    - 0
    name: r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 4.0
  r_e4:
    center:
    - 3.0
    - -2.0
    layer:
    - 49
    - 0
    name: r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 4.0
settings:
  bend:
    function: bend_euler
  coupler_ring:
    function: coupler_ring
  coupler_ring_top: null
  cross_section: xs_sc
  cross_section_heater: xs_heater_metal
  cross_section_waveguide_heater: xs_sc_heater_metal
  gap: 0.2
  gap_top: null
  length_x: 1.0
  length_y: 0.01
  port_orientation: null
  radius: 10.0
  straight:
    function: straight
  straight_heater:
    function: straight
  via_stack:
    function: via_stack
    settings:
      layers:
      - HEATER
      - M2
      - MTOP
      size:
      - 4
      - 4
      vias:
      - null
      - function: via
        settings:
          enclosure: 2
          layer: VIA1
      - function: via
        settings:
          layer: VIA2
  via_stack_offset:
  - 1
  - 0
