info: {}
name: optimal_hairpin
ports:
  e1:
    center:
    - -9.11
    - 0.3
    layer:
    - 1
    - 0
    name: e1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.2
  e2:
    center:
    - -9.11
    - -0.3
    layer:
    - 1
    - 0
    name: e2
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.2
settings:
  layer:
  - 1
  - 0
  length: 10
  num_pts: 50
  pitch: 0.6
  turn_ratio: 4
  width: 0.2
