info:
  dy: 0.0
  length: 31.415
  radius: 10.0
  route_info:
    length: 31.415
    n_bend_90: 2.0
    type: xs_sc
    weight: 31.415
    xs_sc_length: 31.415
name: bend_circular_angle180
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 0.0
    - 20.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  add_bbox: null
  add_pins: true
  angle: 180
  cross_section: xs_sc
  layer: null
  npoints: null
  radius: null
  width: null
