info: {}
name: via_stack_with_offset
ports:
  e1:
    center:
    - -5.0
    - 5.0
    layer:
    - 25
    - 0
    name: e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  e2:
    center:
    - 0.0
    - 10.0
    layer:
    - 25
    - 0
    name: e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  e3:
    center:
    - 5.0
    - 5.0
    layer:
    - 25
    - 0
    name: e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  e4:
    center:
    - 0.0
    - 0.0
    layer:
    - 25
    - 0
    name: e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 10.0
settings:
  layer_offsets: null
  layers:
  - PPP
  - M1
  offsets: null
  size:
  - 10
  - 10
  sizes: null
  vias:
  - null
  - function: via
    settings:
      layer: VIAC
