info:
  add_bbox: null
  add_pins: true
  child_name: straight
  cross_section: xs_sc
  layer: null
  length: 10.0
  npoints: 2
  polarization: te
  route_info:
    length: 10.0
    type: xs_sc
    weight: 10.0
    xs_sc_length: 10.0
  wavelength: 1.53
  width: 0.5
name: straight_add_grating_couplers
ports: {}
settings:
  component:
    function: straight
  component_name: null
  gc_port_name: o1
  get_input_labels_function:
    function: get_input_labels
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  layer_label: null
  select_ports:
    function: select_ports
    settings:
      port_type: optical
