info:
  add_optical_ports_arms: false
  bend:
    function: bend_euler
  child_name: mzi_2e88f57c
  combiner:
    function: mmi2x2
  cross_section: xs_sc
  cross_section_x_bot: null
  cross_section_x_top: null
  delta_length: 10.0
  length_x: 0.1
  length_y: 2.0
  mirror_bot: false
  nbends: 2
  port_e0_combiner: o4
  port_e0_splitter: o4
  port_e1_combiner: o3
  port_e1_splitter: o3
  splitter:
    function: mmi2x2
  straight:
    function: straight
  straight_x_bot: null
  straight_x_top: straight_heater_metal
  straight_y: null
  with_splitter: true
name: mzi_2e88f57c_add_electrical_pads_shortest_b2f49b9e
ports:
  elec-mzi_2e88f57c-1:
    center:
    - 19.6
    - 72.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-1
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-2:
    center:
    - 76.5
    - 72.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-2
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-3:
    center:
    - 25.1
    - 78.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-3
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-4:
    center:
    - 82.0
    - 78.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-4
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-5:
    center:
    - 30.6
    - 72.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-5
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-6:
    center:
    - 87.5
    - 72.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-6
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-7:
    center:
    - 82.0
    - 67.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-7
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-8:
    center:
    - 25.1
    - 67.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-8
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  o1:
    center:
    - -10.0
    - -0.625
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -10.0
    - 0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 117.12
    - 0.625
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 117.12
    - -0.625
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  component:
    component: mzi
    settings:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: xs_sc
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
  layer: M3
  pad: pad
  pad_port_spacing: 50.0
  port_names: null
  port_orientation: 90
  select_ports:
    function: select_ports
    settings:
      port_type: electrical
