info: {}
name: grating_coupler_loss_fiber_array4
ports: {}
settings:
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  pitch: 127.0
