info: {}
name: bend_straight_bend
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 20.0
    - 30.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  angle: 90
  cross_section:
    function: cross_section
    settings:
      add_pins_function_name: add_pins_inside1nm
  direction: ccw
  npoints: 720
  p: 0.5
  straight_length: 10.0
  with_arc_floorplan: true
