info:
  enclosure: 2
  size:
  - 0.7
  - 0.7
  spacing:
  - 2.0
  - 2.0
name: via_enclosure2_layerVIA1
ports: {}
settings:
  bbox_layers: null
  bbox_offset: 0
  enclosure: 2
  gap: null
  layer: VIA1
  size:
  - 0.7
  - 0.7
  spacing:
  - 2.0
  - 2.0
