info:
  n_bends: 144
name: cutback_bend90
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 150.0
    - -0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  cols: 6
  component:
    function: bend_euler
  rows: 6
  spacing: 5
  straight:
    function: straight
  straight_length: 5.0
