info:
  child_name: spiral_inner_io_length20000p0
  length: 19999.999
  polarization: te
  wavelength: 1.53
name: spiral_inner_io_fiber_array
ports:
  loopback_1:
    center:
    - -127.0
    - 46.0
    layer:
    - 1
    - 0
    name: loopback_1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  loopback_4:
    center:
    - -127.0
    - 46.0
    layer:
    - 1
    - 0
    name: loopback_4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o1:
    center:
    - 0.0
    - 50.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 127.0
    - 50.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  N: 6
  add_grating_couplers:
    function: add_grating_couplers_with_loopback_fiber_array
  asymmetric_cross_section: false
  bend180:
    function: bend_euler
    settings:
      angle: 180
  bend90:
    function: bend_euler
  cross_section: xs_sc
  cross_section_bend: null
  cross_section_bend180: null
  grating_spacing: 127.0
  length: 20000.0
  straight:
    function: straight
  waveguide_spacing: 3.0
  x_straight_inner_left: 50.0
  x_straight_inner_right: 150.0
  y_straight_inner_bottom: 10.0
  y_straight_inner_top: 50.0
