info:
  child_name: mmi1x2
  components: 88
  cross_section: xs_sc
  gap_mmi: 0.25
  length_mmi: 5.5
  length_taper: 10.0
  straight:
    function: straight
  taper:
    function: taper
  width: null
  width_mmi: 2.5
  width_taper: 1.0
  with_bbox: true
name: mmi1x2_cutback_splitter
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 438.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend180:
    function: bend_euler
    settings:
      angle: 180
  cols: 4
  component:
    function: mmi1x2
  cross_section: xs_sc
  mirror: false
  port1: o1
  port2: o2
  port3: o3
  rows: 5
  straight_length: null
