info:
  n_bends: 8
name: staircase
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 105.0
    - 100.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  component:
    function: bend_euler
  length_h: 5.0
  length_v: 5.0
  rows: 4
  straight:
    function: straight
